### ISSUE TITLE
So what will cause ”testWhileIdle is true, validationQuery not set“ 

### ISSUE THREAD

**Issue by sequarius** [alibaba/druid#1497]
I am using Spring Boot 1.4.2 and Druid 1.0.26 .I had put 'validationQuery' into my config ,How ever the error of  “testWhileIdle is true, validationQuery not set” is throwed when I made SQL operation，Here is my config
```
spring:
  datasource:
    name: db#01
    url: 
    username: 
    password: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: net.sf.log4jdbc.DriverSpy
    filters: stat
    sessionStatEnable: true
    profileEnable: true
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    maxOpenPreparedStatements: 20
```

so how can i resolve this problem
