### ISSUE TITLE
Spring boot中application.yml配置文件druid属性无法解析

### ISSUE THREAD

**Issue by chuxiongGitHub** [alibaba/druid#1784]
> 在Spring boot中，在application.yml文件中，除了type属性可以解析外，其它的属性不能解析。访问druid数据监控界面，可以正常访问了，但是SQL数据监控一栏为空，我已经访问了几个SQL查询了。可能是配置文件中的属性无法解析的问题。有谁可以帮我看看吗，十分感谢。

![image](https://user-images.githubusercontent.com/17865720/27217203-7aadfbd6-52ab-11e7-93f6-bc28d26eece6.png)
![image](https://user-images.githubusercontent.com/17865720/27217210-85416074-52ab-11e7-804c-a793f21ed9d8.png)
![image](https://user-images.githubusercontent.com/17865720/27217216-8c819fd4-52ab-11e7-9bc2-3c7aa49e600e.png)
![image](https://user-images.githubusercontent.com/17865720/27217224-94f56916-52ab-11e7-83ad-8577cafc8466.png)

**Comment by qq592304796** [comment]
贴一下代码。

**Comment by chuxiongGitHub** [comment]
```
@WebFilter(filterName = "druidWebStatFilter", urlPatterns = arrayOf("/*"),
        initParams = arrayOf(
                WebInitParam(name = "exclusions", value = "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"))
)
class DruidStatFilter : WebStatFilter() {
    private val serialVersionUID: Long = 1L
}
```
***
```
@SuppressWarnings("serial")
@WebServlet(urlPatterns = arrayOf("/druid/*"),
        initParams = arrayOf(
                WebInitParam(name = "allow", value = ""),
                WebInitParam(name = "deny", value = "192.168.1.73"),
                WebInitParam(name = "loginUsername", value = "admin"),
                WebInitParam(name = "loginPassword", value = "123"),
                WebInitParam(name = "restEnable", value = "false"))
)
class DruidStatViewServlet : StatViewServlet() {
}
```
***
```
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521/orcl
    username: RAINBOW
    password: admin123
    type: com.alibaba.druid.pool.DruidDataSource
    validationQuery: select 1 from dual
    filters: stat,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    initialSize: 5
    minIdle: 5
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
```

> 我的配置文件中，从validationQuery 这个属性开始，显示的都是黄色的，写type的都有自动提示出来，但是下面的就没有提示了，鼠标移到上面有警告提示：
![image](https://user-images.githubusercontent.com/17865720/27219608-dd7ba99e-52b4-11e7-86ad-45cf44ad4053.png)
