### ISSUE TITLE
使用springboot 1.5.3 配置 druid yml配置报testWhileIdle is true, validationQuery not set

### ISSUE THREAD

**Issue by yuesf** [alibaba/druid#1825]
使用springboot 1.5.3 配置 druid引入 druid-spring-boot-starter
<dependency>
			<groupId>com.alibaba</groupId>
			<artifactId>druid-spring-boot-starter</artifactId>
			<version>1.1.0</version>
		</dependency>

 yml配置如下
spring:
  datasource:
    url: jdbc:h2:file:~/.h2/aicat;lock_mode=3
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    druid:
      validationQuery: select 1
而 validationQuery 这个识别不出来，并还会说未设置
报错如下：
ERROR 510 --- [pool-1-thread-1] com.alibaba.druid.pool.DruidDataSource   : testWhileIdle is true, validationQuery not set

**Comment by lihengming** [comment]
```
spring:
  datasource:
    url: jdbc:h2:file:./demo-db
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  druid:
    validationQuery: select 1
```
我在```DemoApplication```里试了，没有此问题。
