### ISSUE TITLE
使用druid-spring-boot-starter，Spring Boot的自定义定时任务失效

### ISSUE THREAD

**Issue by liuw518** [alibaba/druid#2040]
在没有使用druid前，在Spring Boot的项目中自定义的任务是可以定时执行的。
使用druid-spring-boot-starter切换为druid的数据源后，自定义的定时任务就不再定时执行了。

于是查找原因，发现将druid的配置改成如下这样后，定时任务可以正常执行。猜测是druid的filter或者什么将定时任务的Bean进行了包装或代理，导致spring的计划任务框架无法扫描到标注了Scheduled的方法，因此导致的定时任务无法执行。
```
#  aop:
#    proxy-target-class: false #不能包含上面一行以及这一行的配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://*******************************
    username: ***********
    password: **********
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      validation-query: select 'x'
      validation-query-timeout: 100
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true

      filter:
        stat:
          enabled: false #必须设置为false

#      filters: stat
      web-stat-filter:
        enabled: false #必须设置为false
#        url-pattern: /*
#        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
#        session-stat-enable: true
#        session-stat-max-count: 1000
#        profile-enable: true
      stat-view-servlet:
        enabled: false #必须设置为false
#        url-pattern: /druid/*
#        reset-enable: true
#      aop-patterns: '*.*'
```
