### ISSUE TITLE
spring boot druid 1.1.6设置ip白名单、黑名单、是否允许清空无效

### ISSUE THREAD

**Issue by BerryWang1996** [alibaba/druid#2342]
falses这样写也没有抛异常，是怎么回事？
代码：
```
@Configuration
public class DruidMonitorConfig {

    /**
     * 访问地址
     */
    private static final String DRUID_MONITOR_URL = "/druid";

    @Bean
    public ServletRegistrationBean DruidStatViewServlet() {
        ServletRegistrationBean bean = new ServletRegistrationBean(new StatViewServlet(), DRUID_MONITOR_URL + "/*");
        // 白名单
        bean.addInitParameter("allow", "192.168.1.6");
        // 黑名单
        bean.addInitParameter("deny", "127.0.0.1");
        // 用户名
        bean.addInitParameter("loginUsername", "admin");
        // 密码
        bean.addInitParameter("loginPassword", "admin");
        // 是否允许清空数据
        bean.addInitParameter("resetEnable", "falses");
        return bean;
    }
}
```
配置文件
```
      filters: config,stat
      filter:
        log4j:
          enabled: true
          statement-executable-sql-log-enable: true
          statement-sql-pretty-format: true
          connection-log-enabled: false
          data-source-log-enabled: false
          statement-log-enabled: false
          result-set-log-enabled: false
        wall:
          enabled: true
```
