### ISSUE TITLE
数据源监控问题

### ISSUE THREAD

**Issue by tuxianchao** [alibaba/druid#2493]
对于单数据源的监控，通过.yml配置文件可以做到，但是对于多数据源怎么配置监控呢。

**Comment by wenshao** [comment]
@lihengming

**Comment by weiboyiyou** [comment]
@tuxianchao 请问如何通过.yml配置文件进行单数据源的监控？

**Comment by tuxianchao** [comment]
@weiboyiyou 参考下
```
spring:
  datasource:
    username: xxx
    password: xxx
    url: jdbc:mysql://ip:3306/xxxx
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT `X`
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      web-stat-filter:
        enable: true
        url-pattern: /*
      stat-view-servlet:
        enable: true
        login-username: xxxx
        login-password: xxxx
        reset-enable: true

      filter:
        stat:
          slow-sql-millis: 2000
          db-type: mysql
          log-slow-sql: true
          enabled: true
        wall:
          db-type: mysql
          enabled: true
          config:
            delete-allow: false
            drop-table-allow: false
      aop-patterns: com.xxx.xxx.Application.controller.*

```
