### ISSUE TITLE
如何自定义StatViewServlet初始化

### ISSUE THREAD

**Issue by OuIChien** [alibaba/druid#2717]
我使用了不一样的配置前缀：
application.yml内容：

```
datasource:
  druid:
    corp:
      stat-view-servlet:
        login-username: @druid.login-username@
```

结果初始化时，属性没注入，请问如何自定义一个，可以读取datasource.druid.corp前缀的属性
