### ISSUE TITLE
使用JNDI配置时,poolPreparedStatements不生效导致oracle报超出游标的错误

### ISSUE THREAD

**Issue by grace-233** [alibaba/druid#2726]
**环境**: spring boot 1.4.1, druid 1.1.10 ,tomcat 7.0.82
**问题描述：**
我在代码中配置连接池并设置poolPreparedStatements没问题，preparedStatements缓存生效。
配置如下:
```
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//10.0.0.200:1521/ORCL
    username: test
    password: test
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource       
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 30
      pool-prepared-statements: true
      max-open-prepared-statements: 100
```
此时 从监控页面可以看到preparedStatements缓存生效了：
```
真实preparedStatements打开次数: 450
真实preparedStatements关闭次数: 350
PSCache访问次数: 1298
PSCache命中次数: 848
PSCache不命中次数：450
```

但是当我在Tomcat中使用JNDI配置数据源的时候，preparedStatements配置生效了。但preparedStatements没有被缓存，导致preparedStatements越来越多， 最后oracle 报`ORA-01000: maximum open cursors exceeded`的错误。
JNDI配置如下:
```
 <Resource 
         name="jdbc/oracle"
         factory="com.alibaba.druid.pool.DruidDataSourceFactory"
         auth="Container" 
         type="javax.sql.DataSource"
         url="jdbc:oracle:thin:@//10.0.0.200:1521/ORCL"
         driverClassName="oracle.jdbc.OracleDriver"
         username="test" 
         password="test"
         filters="config,wall,stat"
         initialSize="3"
         minIdle="3"
         maxActive="30"
         poolPreparedStatements="true"
         asyncInit="true"
/>
```
java:
```
    @Bean(value="dataSource")
    @ConfigurationProperties(prefix="spring.datasource.druid")
    public DataSource dataSource() throws SQLException {
        JndiDataSourceLookup dataSourceLookup = new JndiDataSourceLookup();
        DataSource dataSource = dataSourceLookup.getDataSource("java:comp/env/jdbc/oracle");
        return dataSource;
}
```
监控页面显示:
```
真实preparedStatements打开次数: 1026
真实preparedStatements关闭次数: 0
PSCache访问次数: 1026
PSCache命中次数:0
PSCache不命中次数：1026
```
可以看到虽然PSCache被开启了， 但没有缓存成功，导致打开的preparedStatements越来越多。。最终oracle报错。

请大神帮忙解答，感激不尽~~~~！
