### ISSUE TITLE
1.1.10版本Druid SQL SQL监控页面不显示Sql，请问是内部版本bug？

### ISSUE THREAD

**Issue by yonghu86** [alibaba/druid#2743]
druid-1.1.10版本Druid SQL SQL监控页面不显示Sql，请问是内部版本bug？

**Comment by yonghu86** [comment]
以前用的1.0.20版本是正常的，数据库是sqlserver2014

**Comment by yonghu86** [comment]
> 请问最后解决方法是修改sql.html吗, 还是其他的配置问题?@yonghu86

暂时没有解决呀，坐等官网的更新版本处理。

**Comment by diaodiaofly** [comment]
解决了么  1.1.10 出现同样问题   url监控、spring监控、session监控正常  就sql监控没有数据

**Comment by bangq** [comment]
同样的问题

**Comment by ettingshausen** [comment]
@wenshao `1.1.18` 同样有这个问题

**Comment by yonghu86** [comment]
官方就没人处理这么低级的错？也没调试？这么长时间了bug还在

**Comment by chrzha** [comment]
首先我用的是springboot 2.1.7 + druid 1.1.9也出现同样的问题，sql的监控出不来。
然后参考了这篇文章： https://blog.csdn.net/h378588270/article/details/99593122
其中要注意的是：
1. druid依赖：
`<dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-starter</artifactId>
            <version>1.1.17</version>
        </dependency>`
2. yaml配置的结构，注意druid节点。

**Comment by p555iii** [comment]
同样这个问题  1.1.21版本druid 无法显示 sql 监控页面 ，切回1.0.20后恢复正常

**Comment by ettingshausen** [comment]
> 同样这个问题 1.1.21版本druid 无法显示 sql 监控页面 ，切回1.0.20后恢复正常，什么时候发布新版本哦  

@p555iii 加上过滤器试一下：
```
spring:
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
      filters: stat,wall,slf4j 
      validation-query: select 1
```
