### ISSUE TITLE
监控数据保存，springboot如何配置

### ISSUE THREAD

**Issue by venbill** [alibaba/druid#2957]
请问如果不使用xml配置的情况下，DruidDataSourceStatLogger配置类如何在springboot中配置

**Comment by Ruffianjiang** [comment]
yml没有提供自动提示，属性配置了是起作用的，对应`DruidAbstractDataSource#setStatLoggerClassName(String className)`
```yaml
spring:
  datasource:
    druid:
      stat-logger-class-name: xx.xx.MyStatLogger
```

```java
package xx.xx;

import com.alibaba.druid.pool.DruidDataSourceStatLoggerImpl;
import lombok.extern.slf4j.Slf4j;

@Slf4j
public class MyStatLogger extends DruidDataSourceStatLoggerImpl {

    @Override
    public void log(String value) {
        super.log(value);
        log.info("1============================================");
        log.info("{}", value);
        log.info("2============================================");
    }
}
```
