### ISSUE TITLE
springboot批量执行配置不生效 multi-statement-allow = true

### ISSUE THREAD

**Issue by a471640241** [alibaba/druid#3093]
库 : druid-spring-boot-starter
版本: 1.1.13
```
datasource:
    druid:
      filter:
        wall:
          config:
            multi-statement-allow: true
```
加上这个配置批量执行druid还是不能生效.使用druid1.1.10的时候就不行,三个小版本过去了还没解决吗?
目前只能用@Bean的形式解决,但是会导致filters失效,需要在Bean中再次配置
```
    @Bean
    public DataSource dataSource() throws SQLException {
        DruidDataSource dataSource = DruidDataSourceBuilder.create().build();
        // 设置数据源允许执行多条语句
        WallConfig wallConfig = new WallConfig();
        wallConfig.setMultiStatementAllow(true);
        WallFilter wallFilter = new WallFilter();
        wallFilter.setConfig(wallConfig);
        dataSource.getProxyFilters().add(wallFilter);
        dataSource.setFilters("stat,wall");//配置文件中的配置失效必须手动设置
        return dataSource;
    }
```
#980  这个问题很早就提出来了.
