### ISSUE TITLE
springboot+druid+atomikos 8小时数据后无法使用，多请求几次又可以了

### ISSUE THREAD

**Issue by qiaoyajun520** [alibaba/druid#3187]
Atomikos数据源：
@Bean(name = "dataSourceDmc")
    public DataSource dataSourceDmc() {
        AtomikosDataSourceBean ds = new AtomikosDataSourceBean();
        Properties prop = build(env, "spring.datasource.druid.dmcdb.");
        ds.setXaDataSourceClassName(dataSourceType);
        ds.setPoolSize(5);
        ds.setXaProperties(prop);
        return ds;
    }

yml配置
dmcdb:
        ## JDBC配置
        name: DmcDBConfig
        url: jdbc:mysql://192.168.2.214:3306/test_dmc?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
        username: reborn
        password: 123456
        driverClassName: com.mysql.cj.jdbc.Driver
        filters: stat,wall,slf4j
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        removeAbandoned: false
        removeAbandonedTimeout: 80
        logAbandoned: true

报错信息：
The last packet successfully received from the server was 58,839,119 milliseconds ago. The last packet sent successfully to the server was 58,839,120 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.

**Comment by CQ-Harry** [comment]
朋友，最后解决没有啊？我现在同样的问题。

**Comment by qiaoyajun520** [comment]
> 朋友，最后解决没有啊？我现在同样的问题。

atomikos:
      maxPoolSize: 5
      minPoolSize: 0
      openTestQuery: false
    druid:
      ## 连接池配置
      userdb:
        ## JDBC配置
        name: UserDBConfig
        url: jdbc:mysql://xxxx
        username: reborn
        password: 123456
        driverClassName: com.mysql.cj.jdbc.Driver
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall,slf4j
        maxActive: 20
        initialSize: 1
        maxWait: 6000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1
        validationQueryTimeout: 2000
        keepAlive: true
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        removeAbandoned: false
        removeAbandonedTimeout: 80
        logAbandoned: true

    @Primary
    @Bean(name = "dataSourceUser")
    public DataSource dataSourceUser() {
        AtomikosDataSourceBean ds = new AtomikosDataSourceBean();
        Properties prop = build(env, "spring.datasource.druid.userdb.");
        ds.setXaDataSourceClassName(dataSourceType);
        ds.setMaxPoolSize(maxPoolSize);
        ds.setMinPoolSize(minPoolSize);
        ds.setXaProperties(prop);
        if (openTestQuery) {
            ds.setTestQuery("select 1");
        }
        return ds;
    }


把AtomikosDataSourceBean 的最小连接池minPoolSize设为0，问题暂时解决了。

**Comment by CQ-Harry** [comment]
> > 朋友，最后解决没有啊？​​我现在同样的问题。
> 
> atomikos：
> maxPoolSize：5 
> minPoolSize：0 openTestQuery 
> ：false
> 
> ```
> druid:
>   ## 连接池配置
>   userdb:
>     ## JDBC配置
>     name: UserDBConfig
>     url: jdbc:mysql://xxxx
>     username: reborn
>     password: 123456
>     driverClassName: com.mysql.cj.jdbc.Driver
>     # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
>     filters: stat,wall,slf4j
>     maxActive: 20
>     initialSize: 1
>     maxWait: 6000
>     minIdle: 1
>     timeBetweenEvictionRunsMillis: 60000
>     minEvictableIdleTimeMillis: 300000
>     validationQuery: select 1
>     validationQueryTimeout: 2000
>     keepAlive: true
>     testWhileIdle: true
>     testOnBorrow: false
>     testOnReturn: false
>     poolPreparedStatements: true
>     maxOpenPreparedStatements: 20
>     removeAbandoned: false
>     removeAbandonedTimeout: 80
>     logAbandoned: true
> 
> @Primary
> @Bean(name = "dataSourceUser")
> public DataSource dataSourceUser() {
>     AtomikosDataSourceBean ds = new AtomikosDataSourceBean();
>     Properties prop = build(env, "spring.datasource.druid.userdb.");
>     ds.setXaDataSourceClassName(dataSourceType);
>     ds.setMaxPoolSize(maxPoolSize);
>     ds.setMinPoolSize(minPoolSize);
>     ds.setXaProperties(prop);
>     if (openTestQuery) {
>         ds.setTestQuery("select 1");
>     }
>     return ds;
> }
> ```
> 把AtomikosDataSourceBean的最小连接池minPoolSize设为0，问题暂时解决了。

感谢！

**Comment by CQ-Harry** [comment]
@qiaoyajun520 改成0依然不行，-_-

**Comment by qiaoyajun520** [comment]
> @qiaoyajun520 改成0依然不行，-_-

把你的配置信息贴出来看一下

**Comment by CQ-Harry** [comment]
> > @qiaoyajun520 改成0依然不行，-_-
> 
> 把你的配置信息贴出来看一下

`
/**
     * 数据源创建模板
     */
    private static DataSource createDataSource(String dataSourceName, DruidProperties druidProperties) {
        AtomikosDataSourceBean atomikosDataSourceBean = new AtomikosDataSourceBean();
        atomikosDataSourceBean.setXaDataSourceClassName("com.alibaba.druid.pool.xa.DruidXADataSource");
        atomikosDataSourceBean.setUniqueResourceName(dataSourceName);
        atomikosDataSourceBean.setXaProperties(druidProperties.createProperties());
        atomikosDataSourceBean.setMinPoolSize(0);
        return atomikosDataSourceBean;
    }
 public Properties createProperties() {
        Properties properties = new Properties();
        properties.put("url", this.url);
        properties.put("username", this.username);
        properties.put("password", this.password);
        properties.put("driverClassName", this.driverClassName);
        properties.put("initialSize", this.initialSize);
        properties.put("maxActive", this.maxActive);
        properties.put("minIdle", this.minIdle);
        properties.put("maxWait", this.maxWait);
        properties.put("poolPreparedStatements", this.poolPreparedStatements);
        properties.put("maxPoolPreparedStatementPerConnectionSize", this.maxPoolPreparedStatementPerConnectionSize);
        properties.put("validationQuery", this.validationQuery);
        properties.put("testOnBorrow", this.testOnBorrow);
        properties.put("testOnReturn", this.testOnReturn);
        properties.put("testWhileIdle", this.testWhileIdle);
        properties.put("timeBetweenEvictionRunsMillis", this.timeBetweenEvictionRunsMillis);
        properties.put("minEvictableIdleTimeMillis", this.minEvictableIdleTimeMillis);
        properties.put("filters", this.filters);
        properties.put("keepAlive", true);
        return properties;
    }
`
`spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      iot:  #数据源1
        url: jdbc:mysql://127.0.0.1:3306/dev_authz?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password:
      hzx:  #数据源2
        url: jdbc:mysql://127.0.0.1:3306/dev_hzx?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password:
      smalltools:  #数据源3
        url: jdbc:mysql://127.0.0.1:3306/dev_smalltools?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password:
      activiti:  #数据源4
        url: jdbc:mysql://127.0.0.1:3306/dev_hzx?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password:
      initial-size: 10
      max-active: 100
      min-idle: 5
      max-wait: 600
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
      #      filters: config,wall,log4j`

**Comment by CQ-Harry** [comment]
`
spring:
  redis:
    password:      # 密码（默认为空）
    # 连接池中连接池中的最大空闲连接的最小空闲连接
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      iot:  #数据源1
        url: jdbc:mysql://127.0.0.1:3306/dev_authz?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password:
      hzx:  #数据源2
        url: jdbc:mysql://127.0.0.1:3306/dev_hzx?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password:
      smalltools:  #数据源3
        url: jdbc:mysql://127.0.0.1:3306/dev_smalltools?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password:
      activiti:  #数据源4
        url: jdbc:mysql://127.0.0.1:3306/dev_hzx?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password:
      initial-size: 10
      max-active: 100
      min-idle: 5
      max-wait: 600
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
      #      filters: config,wall,log4j
`

**Comment by CQ-Harry** [comment]
> > @qiaoyajun520 改成0依然不行，-_-
> 
> 把你的配置信息贴出来看一下

```
spring:
  redis:
    password:      # 密码（默认为空）
    # 连接池中连接池中的最大空闲连接的最小空闲连接
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      iot:  #数据源1
        url: jdbc:mysql://127.0.0.1:3306/dev_authz?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password:
      hzx:  #数据源2
        url: jdbc:mysql://127.0.0.1:3306/dev_hzx?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password:
      smalltools:  #数据源3
        url: jdbc:mysql://127.0.0.1:3306/dev_smalltools?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password:
      activiti:  #数据源4
        url: jdbc:mysql://127.0.0.1:3306/dev_hzx?autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password:
      initial-size: 10
      max-active: 100
      min-idle: 5
      max-wait: 600
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
      #      filters: config,wall,log4j
```
