### ISSUE TITLE
配置url-pattern后登陆页面重定向地址错误

### ISSUE THREAD

**Issue by kkwwang** [alibaba/druid#3257]
我的`stat-view-servlet`部分配置如下：
```
spring:
    datasource:
        druid:
            stat-view-servlet:
                enabled: true
                url-pattern: /db/*
                login-username: username
                login-password: password
```
访问`http://localhost:port/db/index.html`时被重定向到`ttp://localhost:8082/druid/login.html`请求返回`404`
