### ISSUE TITLE
配置多数据源后，JMX 中只显示单一数据源监控内容

### ISSUE THREAD

**Issue by Elderry** [alibaba/druid#3291]
我配置多数据源后，jmx 中只出现了一个数据源的数据，请问如何解决？
![image](https://user-images.githubusercontent.com/1892221/59318795-dbde4380-8cfa-11e9-8b5b-9faba35224b0.png)
相关配置：
```
spring:
  application:
    name: ${service.name}
  profiles:
    active: ${STACK_NAME:test}
  datasource:
    druid:
      own:
        name: druidcp-own
        continue-on-error: false
        initialize: true
        url: "jdbc:mysql://${OWN_DB_ADDRESS:localhost}:${OWN_DB_PORT:4306}/own"
        ...
      external:
        name: druidcp-external
        continue-on-error: false
        initialize: true
        url: "jdbc:mysql://${EXTERNAL_DB_ADDRESS:localhost}:${EXTERNAL_DB_PORT:4306}/external"
        ...
```
注入 DataSource：
```
    @Primary
    @Bean(name = "ownDataSource")
    @ConfigurationProperties(prefix = "spring.datasource.druid.own")
    public DataSource dataSource() {
        return DruidDataSourceBuilder.create().build();
    }
    @Bean(name = "externalDataSource")
    @ConfigurationProperties(prefix = "spring.datasource.druid.external")
    public DataSource dataSource() {
        return DruidDataSourceBuilder.create().build();
    }
```
