### ISSUE TITLE
yml 中 comment-allow 配置不起作用

### ISSUE THREAD

**Issue by Ethanzyc** [alibaba/druid#3546]
```yaml
datasource:
  druid:
      filter:
        wall:
          config:
            comment-allow: true
```
这边打了断点并没有走进来
![image](https://user-images.githubusercontent.com/34021210/68171666-aab72600-ffaf-11e9-8f73-2bd6f7c19823.png)
sql 执行时 config.isCommentAllow() = false
![image](https://user-images.githubusercontent.com/34021210/68171577-4ac07f80-ffaf-11e9-8da5-44211049e06a.png)
这是druid相关所有配置
```yaml
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
#      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      url: jdbc:mysql://****:**/**?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
      username: **
      password: **
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 30000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,slf4j,wall

      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: **
        login-password: **

      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 1000
          db-type: mysql
          merge-sql: true
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-log-enabled: false
          statement-executable-sql-log-enable: true
          statement-log-error-enabled: true
          result-set-log-enabled: true
        wall:
          config:
            comment-allow: true
```
