### ISSUE TITLE
druid 与 p6spy整合出错

### ISSUE THREAD

**Issue by DimonHo** [alibaba/druid#3621]
![image](https://user-images.githubusercontent.com/3371641/70696116-033fb880-1cfe-11ea-88a8-615a1bcdbd83.png)

感觉druid自带的sql日志打印太不直观，于是把p6spy整合进来，在这一步判断自动判断数据库类型的时候报错
![image](https://user-images.githubusercontent.com/3371641/70696318-69c4d680-1cfe-11ea-89d9-87a913fcfafb.png)
无法识别`jdbc:p6spy:mysql:`导致获取dbType空指针异常

**Comment by DimonHo** [comment]
该异常会再开启了wallFilter后出现

**Comment by DimonHo** [comment]
继续跟踪了一下源码，发现了解决办法
### 解决办法：
既然是自动识别不了，我们可以手动明确指定db-type
```
spring:
  datasource:
    druid:
      db-type: mysql
```
