### ISSUE TITLE
starter 中DruidDataSource连接池配置问题请教

### ISSUE THREAD

**Issue by dongxingong** [alibaba/druid#3742]
有个疑问想请教下，DruidDataSource 中连接池配置 configFromPropety(properties) ，System.getProperties()是如何取到spring中的连接池配置的， 我用yml配置文件，默认不会写入System.Properties
```yml
spring: 
 datasource:
   druid:
      initial-size: 50
      time-between-eviction-runs-millis: 60000 
      max-active: 50
```
