### ISSUE TITLE
druid-spring-boot-starter目前对springboot2 webflux有支持吗？

### ISSUE THREAD

**Issue by wuxijie** [alibaba/druid#3785]
druid-spring-boot-starter目前对springboot2 webflux有支持吗？

**Comment by SnowZhouJ** [comment]
目前webflux下druid是可以用的，只是监控界面访问不了，这个后续应该考虑支持一下webflux的监控界面访问的问题

**Comment by SnowZhouJ** [comment]
@argan webflux的监控界面访问的问题，有计划解决吗？

**Comment by zhaoyou** [comment]
@SnowZhouJ 就算不用监控页面 怎么配置可以支持，启动一直报找不到Servlet
```
Caused by: java.lang.ClassNotFoundException: javax.servlet.Servlet

```


```
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: password
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
```
