### ISSUE TITLE
自定义DruidDataSource的实现, 如果通过application.yml文件配置

### ISSUE THREAD

**Issue by liuboren0617** [alibaba/druid#4271]
自定义了DruidDataSource,通过修改type为自己的cn.sunline.edsp.postgresql.druid.MyDruidDataSource没有生效
````
spring:
  datasource:
    type: cn.sunline.edsp.postgresql.druid.MyDruidDataSource
    #    platform: postgres
    druid:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://192.168.217.128:5432/postgres
      username: postgres
      password: password
      其他参数略..
````

是我配置的不对 吗?
