### ISSUE TITLE
1.2.8版本druid-admin收集对应服务数据空指针问题

### ISSUE THREAD

**Issue by 345538832** [alibaba/druid#4654]
注册中心使用nacos，在获取nacos服务列表时，获取到druid-admin服务的instanceId为空出现空指针。
bootstrap.yml配置
```
server:
  port: 19999
spring:
  application:
    name: druid-admin
  main:
    allow-bean-definition-overriding: true
  cloud:
    consul:
      enabled: false
      host: localhost
      port: 8500
      discovery:
        enable: true
        hostname: ${spring.cloud.client.ip-address}
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        instance-zone: zone1
    nacos:
      discovery:
        enabled: true
        server-addr: http://122.168.5.218:8848
eureka:
  instance:
    preferIpAddress: true
    ipAddress: localhost
    instance-id: ${eureka.instance.ipAddress}:${server.port}:${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: false

monitor:
  applications: #需要监控的服务名spring.application.name
    - guideAssistant-mini
  login-username: admin #监控页面的登录用户名和密码
  login-password: 123456

```

![image](https://user-images.githubusercontent.com/95165917/148523819-9cd5dd99-2426-484b-93ed-43c0242623d7.png)
![image](https://user-images.githubusercontent.com/95165917/148524608-d36b1da8-a772-42cb-b91e-fee31941266e.png)
