### ISSUE TITLE
Druid连接池dbType获取失败会导致NullPointerException的问题

### ISSUE THREAD

**Issue by yangpanwww** [alibaba/druid#5389]
**问题描述**：
Druid连接池在连接TDengine数据库的时候，无法通过驱动和URL获取数据库的类型，导致NullPointerException的问题

**临时处理**：
手动指定dbType

**问题重现**：
1、依赖, 1.2.17、 1.2.18 都有问题，目前就看到这两个，都有问题， 老版本1.1.10 正常

```xml
       
       <!-- TD驱动开始 -->
        <dependency>
            <groupId>com.taosdata.jdbc</groupId>
            <artifactId>taos-jdbcdriver</artifactId>
            <version>2.0.38</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>30.1.1-jre</version>
        </dependency>
        <!-- TD驱动结束 --> 

        <!-- druid连接池 --> 
       <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid</artifactId>
            <version>1.2.18</version>
        </dependency>
```

2、配置

```yml
      driver-class-name: com.taosdata.jdbc.rs.RestfulDriver
      url: jdbc:TAOS-RS://10.10.0.26:6041/log_center?timezone=Asia/Beijing&charset=utf-8&httpPoolSize=10
      ## 用户名
      username: root
      ## 密码
      password: zQ46Cu#fLlv2
      ## 校验连接sql（可选）, 默认： select server_status()
      validationQuery: select server_status();

```

3、在访问新增或修改时，提示 NullPointerException

**问题代码段**：

DruidAbstractDataSource类，第 **1746** 行代码， dbTypeName 为null导致 NullPointerException，代码片段如下：
```java
            } else if (dbTypeName.equals(DbType.sqlserver.name())) {
                // see https://learn.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-ver16
                physicalConnectProperties.put("loginTimeout", Long.toString(TimeUnit.MILLISECONDS.toSeconds(connectTimeout)));
                if (socketTimeout > 0) {
                    // As SQLServer-jdbc-driver 6.1.2 can use this, see https://github.com/microsoft/mssql-jdbc/wiki/SocketTimeout
                    physicalConnectProperties.put("socketTimeout", Integer.toString(socketTimeout));
                }
            }

```
