### ISSUE TITLE
初始化连接，在出现异常后，inited属性仍然置为 true，导致后续无法重新连接至数据库

### ISSUE THREAD

**Issue by HanYi001** [alibaba/druid#5438]
手动配置数据库连接源，
```
spring:
  datasource:
    clickhouse:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
      url: jdbc:clickhouse://${mc.clickhouse.host}:${mc.clickhouse.port}/manage_center?socket_timeout=300000
      username: ${mc.clickhouse.username}
      password: ${mc.clickhouse.password}
      initial-size: 5 # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      min-idle: 10 # 最小连接池数量
      maxActive: 20 # 最大连接池数量
      maxWait: 60000 #配置获取连接等待超时的时间
      timeBetweenEvictionRunsMillis: 60000 #配置间隔多久进行一次检测，检测需要关闭的空闲连接，单位毫秒
      minEvictableIdleTimeMillis: 600000 #配置一个连接在连接池中的最小生存时间，单位毫秒
      maxEvictableIdleTimeMillis: 900000
      validationQuery: select 'x' #用来检测连接是否有效的sql

      testWhileIdle: true # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。

      testOnBorrow: false #	申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      testOnReturn: false # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
#      breakAfterAcquireFailure: false # 数据库服务宕机自动重连机制
```

```
@Configuration
@MapperScan(
        basePackages = {
                "com.fujin.mapper.clickhouse"},
        sqlSessionFactoryRef = "sqlSessionFactoryClickHouse")
public class MybatisClickHouseConfig {

    @Bean(name = "clickhouse")
    @ConfigurationProperties(prefix = "spring.datasource.clickhouse")
    public DataSource dataSourceClickHouse() {
        return new DruidDataSource();
    }

    @Bean(name = "sqlSessionFactoryClickHouse")
    public SqlSessionFactory sqlSessionFactoryClickHouse(@Qualifier("clickhouse") DataSource dataSource) throws Exception {
        SqlSessionFactoryBean factoryBean = new SqlSessionFactoryBean();
        factoryBean.setDataSource(dataSource); // 连接 clickhouse 库
        factoryBean.setMapperLocations(
                ArrayUtils.addAll(
                        new PathMatchingResourcePatternResolver().getResources("classpath*:mapper/clickhouse/*.xml")
                )
        );
        return factoryBean.getObject();
    }

    @Bean(name = "sqlSessionTemplateClickHouse")
    public SqlSessionTemplate sqlSessionTemplateClickHouse(@Qualifier("sqlSessionFactoryClickHouse") SqlSessionFactory sqlSessionFactory) throws Exception {
        return new SqlSessionTemplate(sqlSessionFactory); // 使用上面配置的Factory
    }
}
```
由于我们线上环境的clickhouse数据库服务启动很慢，所以我故意停止数据库服务进行测试。
1.首先启动java微服务
2.发送请求
此时数据库进行初始化连接，会出现失败，将inited属性这是为true，导致后续请求也会失败
3.恢复数据库服务
4.再次发送请求，仍然请求失败
