### ISSUE TITLE
报错：maxEvictableIdleTimeMillis must be grater than minEvictableIdleTimeMillis

### ISSUE THREAD

**Issue by JiakunXu** [alibaba/druid#5679]
jdk: 17.0.9
tomcat: 10.1.17
spring-boot-starter-parent: 3.2.1
druid-spring-boot-3-starter: 1.2.21
application.yml
```
spring:
  datasource:
    druid:
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 900000
```
启动时 报错
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'spring.datasource.druid.connection' to com.alibaba.druid.pool.DruidPooledConnection:

    Reason: java.sql.SQLException: maxEvictableIdleTimeMillis must be grater than minEvictableIdleTimeMillis

Action:

Update your application's configuration
```
